### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by bouncer1798** [11jo/Icewind_EET#7]
I am getting the followin error om my install.

[tb#compile_patches/icewind_eet\dlg\iwd1_pdialog.d] LEXER ERROR at line 2 column 1-19
Near Text: !
	invalid character [!]
ERROR: parsing [tb#compile_patches/icewind_eet\dlg\iwd1_pdialog.d]: Parsing.Parse_error
ERROR: compiling [icewind_eet\dlg\iwd1_pdialog.d]!
[WeiDU.log]

Stopping installation because of error.

I am attaching my weidu.log file.

(https://github.com/The-Gate-Project/Icewind_EET/files/14229314/WeiDU.log)

**Comment by 11jo** [comment]
I've never encountered this error before, but it seems someone had the same problem [a few years ago,](https://arcanecoast.ru/forum/viewtopic.php?t=1247&start=660) unfortunately no real explanation about it...

Sorry I'm not going to be very helpful.

Your weidu.log shows so many mods and your installation order is not ideal.

It will be difficult to find the one(s) causing the issue.

You can post your SETUP-ICEWIND_EET.DEBUG, additional information might help, but it's a long shots.

**Comment by bouncer1798** [comment]
I tried to submit the debug file in the initial post but it looks like the .debug file extension is not allowed. If I only install the IWD mods then I don't get the error so I assume it could be due to a mod incompability. If you say my install order is not ideal, where am I going wrong? I was under the impression that the basic guidelines for install order are as below:

1. Core Fixes and Tweaks
2. Content Mods
3. NPC Mods
4. Quest Mods
5. Item and Balance Mods
6. Graphics and Sound Mods
7. Compatibility Patches

**Comment by 11jo** [comment]
You're right, your installation order isn't that bad.

But usually :
- UI mod (dragonspearUI) are installed at the beginning.
- Tweaks mods at the end.

The main issue with this installation is the number of mods, you have installed pretty much everything, so there's good chance some of them have incompatibilities.

But it's not the issue here.

If I have to guess I would say one of the npc mods it's likely to have an issue or an oddities that Icewind-EET cannot manage.
But I am not enough experienced to be sure.

Your debug could be helpfull because  it's possible that it's show what files cause the problem.

> `looks like the .debug file extension is not allowed.`

You can change the **.debug** to **.log or .txt** and it should be allowed to be posted.

**Comment by bouncer1798** [comment]
I managed to find a mod that is causing this error: Gavin NPC mod for BG1 and BG2. Attached is a weidu log and a setup-debug file.

[WeiDU.log](https://github.com/The-Gate-Project/Icewind_EET/files/14893867/WeiDU.log)
[Setup-icewind_eet.log](https://github.com/The-Gate-Project/Icewind_EET/files/14893871/Setup-icewind_eet.log)

Edit: Other mods that also give a likewise error:
Saradas Magic for BG2
Haldamir NPC

**Comment by 11jo** [comment]
Re !

Thanks for your debug.

I've informed Tipun, the author, and he should look into the issue.

**Comment by 11jo** [comment]
Hello ! @bouncer1798 

With the last commit I think the probleme is resolved !!! 

If you want to test again on your side...

**Comment by bouncer1798** [comment]
It is working! Thanks so much!!
